[package]
name = "razor-nvpair"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
razor-libnvpair = { version = "0.1", path = "../libnvpair" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
# uuid = { version = "0.8", features = ["serde", "v4"] }
