[package]
name = "razor-nvpair"
version = "0.1.3"
edition = "2021"

[dependencies]
libc = "0.2"
razor-libnvpair = { version = "0.1", path = "../libnvpair" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
