[package]
name = "razor-zfscore-sys"
version = "0.1.2"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2"
razor-libnvpair = { version = "0.1", path = "../libnvpair" }


[build-dependencies]
bindgen = "0.59"
