.test:cargo:
  stage: test
  script:
    - apt update
    - apt install -y libzfslinux-dev
    #- apt install -y llvm-dev libclang-dev clang
    - apt install -y apt-transport-https ca-certificates
    - apt install -y lsb-release wget software-properties-common
    - wget https://apt.llvm.org/llvm.sh
    - chmod +x llvm.sh
    - sudo ./llvm.sh 10
    - cargo fmt -- --check
    - cargo clippy --all-targets
    - cargo test

stages:
  - test

stable:test:
  extends: .test:cargo
  image: rustdocker/rust:stable

beta:test:
  extends: .test:cargo
  image: rustdocker/rust:beta

nightly:test:
  extends: .test:cargo
  image: rustdocker/rust:nightly
