.test:cargo:
  image: ubuntu:focal
  stage: test
  #tags:
  #  - arm64_focal
  before_script:
    - apt update
    - apt install -y build-essential curl
    - apt install -y libzfslinux-dev
    - apt install -y llvm-dev libclang-dev clang
    - curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain $RUST_TOOLCHAIN
    - export PATH="/root/.cargo/bin:${PATH}"
  script:
    #- apt install -y apt-transport-https ca-certificates
    #- apt install -y lsb-release wget software-properties-common
    #- wget https://apt.llvm.org/llvm.sh
    #- chmod +x llvm.sh
    #- sudo ./llvm.sh 10
    #- wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    #- apt-add-repository "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main"
    #- apt-get update
    #- apt -o Acquire::AllowInsecureRepositories=true update
    #- apt-get install -y clang-3.9 lldb-3.9
    - cargo fmt -- --check
    - cargo clippy --all-targets
    - cargo test -- --nocapture

stages:
  - test
  - build

stable:test:
  variables:
    RUST_TOOLCHAIN: stable
  #tags:
  #  - zfs_runner
  extends: .test:cargo
  #image: rustdocker/rust:stable

.beta:test:
  variables:
    RUST_TOOLCHAIN: beta
  #tags:
  #  - zfs_runner
  extends: .test:cargo
  #image: rustdocker/rust:beta

nightly:test:
  variables:
    RUST_TOOLCHAIN: nightly
  #tags:
  #  - zfs_runner
  extends: .test:cargo
  #image: rustdocker/rust:nightly

image:build:
  stage: build
  image: docker:git
  tags:
    - "ondemand"
  services:
    - docker:dind
  rules:
    - if: '$BUILD_DOCKER == "true"'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
  before_script:
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com" > ~/.git-credentials
    - chmod 0600 ~/.git-credentials
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --secret id=git,src=$HOME/.git-credentials -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  after_script:
    - rm ~/.git-credentials
