[workspace]
members = [
    "libnvpair-sys",
    "libnvpair",
    "nvpair",
    "libzfscore-sys",
    "libzfs",
    "libzfscore",
    "zfs",
    "property",
    #    "zfsrpc",
    #    "zfsrpc-cli",
    #    "zfsrpc-client",
    #    "rpc-server",
    #    "zpool-client",
    #    "ztool",
    #    "tracing",
    #    "tracing-client",
]
