[workspace]
members = [
    "libnvpair-sys",
    "libnvpair",
    "nvpair",
    "uutil-sys",
    #"serde-nvpair",
    "zfscore-sys",
    "zfscore",
    "zfs",
    "zfsrpc",
    "rpc-client",
    "rpc-server",
    "tracing"
]
resolver = "2"
