[workspace]
members = [
    "libnvpair-sys",
    "libnvpair",
    "nvpair",
    "zfscore-sys",
    "zfscore",
    "zfs",
    "zfsrpc",
    "zfsrpc-cli",
    "zfsrpc-client",
    "property",
    "rpc-server",
    "zpool-client",
    "ztool",
    "tracing",
    "tracing-client",
]
