[workspace]
members = [
    "libnvpair-sys",
    "libnvpair",
    "nvpair",
    "zfscore-sys",
    "zfscore",
    "zfs",
    "property",
#    "zfsrpc",
#    "zfsrpc-cli",
#    "zfsrpc-client",
#    "rpc-server",
#    "zpool-client",
#    "ztool",
#    "tracing",
#    "tracing-client",
]
