[package]
name = "zfsrpc"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.9", features = ["macros", "rt-multi-thread"] }
razor-zfs= { version = "0.1.0", path = "../zfs" }
tonic = "0.5"
paste = "1.0"
prost = "0.8"
prop-macro = {version = "0.1", path = "../prop-macro"}
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-appender = "0.1"
anyhow = "1.0"

[build-dependencies]
tonic-build = "0.5"

[lib]
name = "zfsrpc"

[[bin]]
name = "client"

[[bin]]
name = "server"

