[package]
name = "ztool"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.9", features = ["macros", "rt-multi-thread"] }
razor-zfsrpc = { version = "0.1", path = "../zfsrpc" }
tracing-subscriber = "0.2"
structopt = "0.3"
walkdir = "2.3"
tracing = "0.1"
anyhow = "1.0"

[features]
dirty = []
