[package]
name = "razor-zfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
razor-nvpair = {version = "0.1", path = "../nvpair"}
razor-zfscore-sys = {version = "0.1", path = "../zfscore-sys"}
razor-zfscore = {version = "0.1", path = "../zfscore"}
serde_with = { version = "1.6", features = ["chrono"] }
thiserror = "1.0"
libc = "0.2"
log = "0.4"
once_cell = "1.8"
