[package]
name = "razor-zfs"
version = "0.4.0"
edition = "2021"
description = "Idiomatic zfs API"
repository = "https://github.com/razor-zfs/razor-rs"
readme = "../README.md"
license = "MIT OR Apache-2.0"
keywords = ["zfs"]
categories = ["api-bindings"]

[dependencies]
libc = "0.2"
log = "0.4"
once_cell = "1.8"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "1.6", features = ["chrono"] }
thiserror = "1.0"
tokio = { version = "1.17", features = ["process"], optional = true }

razor-nvpair = { version = "0.4", path = "../nvpair" }
razor-libzfscore = { version = "0.4", path = "../libzfscore" }
razor-property = { version = "0.4", path = "../property" }

[dev-dependencies]
nanoid = "0.4"

[features]
cmd = ["tokio"]
