[package]
name = "razor-rpc-server"
version = "0.1.0"
edition = "2018"

[dependencies]
razor-zfsrpc = { version = "0.1", path = "../zfsrpc" }
tokio = { version = "1.9", features = ["full"] }
tonic = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
anyhow = "1.0"