[package]
name = "razor-rpc-server"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
razor-zfsrpc = { version = "0.1", path = "../zfsrpc", features = ["dirty"] }
razor-tracing = {version = "0.1", path = "../tracing"}
tokio = { version = "1.9", features = ["full"] }
tonic = "0.5"

# [[bin]]
# name = "razor-rpc-server"
